// Armory data - complete list from Snow Crows
const armoryData = [
    {id: 1466, name: "Trident"},
    {id: 1465, name: "Spite Trait Line"},
    {id: 1464, name: "Speargun"},
    {id: 1463, name: "Form of the Dervish"},
    {id: 1462, name: "Form of the Warrior"},
    {id: 1461, name: "Form of the Mesmer"},
    {id: 1460, name: "Finish"},
    {id: 1459, name: "Adventure"},
    {id: 1458, name: "Keep It Down"},
    {id: 1457, name: "Eat Toxic Bacon"},
    {id: 1456, name: "Itzel Poison Lore"},
    {id: 1455, name: "Nuhoch Wallow"},
    {id: 1454, name: "Berserker Strain"},
    {id: 1453, name: "Resourcefulness"},
    {id: 1452, name: "Secrets Unearthed"},
    {id: 1451, name: "Magic Mirror"},
    {id: 1450, name: "Chest"},
    {id: 1449, name: "Mystic Forge"},
    {id: 1448, name: "Antiquated Ducat"},
    {id: 1447, name: "Aether-Rich Sap"},
    {id: 1446, name: "Castoran Intuition"},
    {id: 1445, name: "Chant"},
    {id: 1444, name: "Snow Crows"},
    {id: 1442, name: "Demolish"},
    {id: 1441, name: "Obliterate"},
    {id: 1439, name: "Thorns"},
    {id: 1436, name: "Ascended Shard of Glory"},
    {id: 1435, name: "PvP League Ticket"},
    {id: 1434, name: "Note"},
    {id: 1433, name: "Willing Host"},
    {id: 1432, name: "Titanic Strain"},
    {id: 1431, name: "Replicating Strain"},
    {id: 1430, name: "Blur"},
    {id: 1429, name: "Arrow"},
    {id: 1428, name: "Raptor Swiftwing"},
    {id: 1427, name: "ritualist attempt"},
    {id: 1426, name: "Ritualist Shroud"},
    {id: 1425, name: "Overheat"},
    {id: 1424, name: "sigil of energy"},
    {id: 1423, name: "Sigil of exposure"},
    {id: 1422, name: "sigil of exploitation"},
    {id: 1421, name: "sigil of cleansing"},
    {id: 1420, name: "transference sigil"},
    {id: 1419, name: "avatar amulet"},
    {id: 1418, name: "carrion amulet"},
    {id: 1417, name: "berserker amulet"},
    {id: 1416, name: "Cyclone Bow"},
    {id: 1415, name: "Fishing"},
    {id: 1414, name: "Hero Point"},
    {id: 1413, name: "Hero Point"},
    {id: 1412, name: "Volatile Magic"},
    {id: 1411, name: "Mistborn Mote"},
    {id: 1410, name: "Logging Axe"},
    {id: 1409, name: "Mining Pick"},
    {id: 1408, name: "Harvesting Sickle"},
    {id: 1407, name: "Winterberry"},
    {id: 1406, name: "Unbound Magic"},
    {id: 1405, name: "Tyrian Defense Seal"},
    {id: 1404, name: "Unidentified Gear"},
    {id: 1403, name: "Pristine Dragon Eye"},
    {id: 1402, name: "Radiant Forge"},
    {id: 1401, name: "Cosmic Wisdom"},
    {id: 1400, name: "Visions of Eternity (VoE)"},
    {id: 1399, name: "Selfless Spirit"},
    {id: 1398, name: "Selfish Spirit"},
    {id: 1396, name: "True Nature"},
    {id: 1395, name: "Facet of Nature—Dragon"},
    {id: 1394, name: "Facet of Nature—Dwarf"},
    {id: 1393, name: "Facet of Nature—Demon"},
    {id: 1392, name: "Facet of Nature—Centaur"},
    {id: 1391, name: "Facet of Nature—Assassin"},
    {id: 1388, name: "Shadow Shroud"},
    {id: 1387, name: "soul shards"},
    {id: 1386, name: "Agony Resistance"},
    {id: 1385, name: "Mistlock Singularity"},
    {id: 1384, name: "Legendary Weapon Starter Key - Universal"},
    {id: 1383, name: "Ritualist's Insignia"},
    {id: 1382, name: "Mirage Mirror"},
    {id: 1381, name: "Luminary's Blessing"},
    {id: 1380, name: "Wind Force"},
    {id: 1379, name: "Photon Forge"},
    {id: 1378, name: "Conduit"},
    {id: 1377, name: "Luminary"},
    {id: 1376, name: "Paragon"},
    {id: 1375, name: "Evoker"},
    {id: 1374, name: "Troubadour"},
    {id: 1373, name: "Ritualist"},
    {id: 1372, name: "Galeshot"},
    {id: 1371, name: "Amalgam"},
    {id: 1370, name: "Antiquary"},
    {id: 1369, name: "Steelstar's Insignia"},
    {id: 1367, name: "Willbender Flames"},
    {id: 1366, name: "Soldier's Focus"},
    {id: 1365, name: "Transfusion"},
    {id: 1364, name: "Detonate Cartridges"},
    {id: 1363, name: "Malefic Darkness Immunity"},
    {id: 1362, name: "Malefic Darkness"},
    {id: 1360, name: "Scan for Rift"},
    {id: 1359, name: "Sniff"},
    {id: 1358, name: "Mentor"},
    {id: 1357, name: "South Meta Event"},
    {id: 1356, name: "Middle Meta Event"},
    {id: 1355, name: "North Meta Event"},
    {id: 1354, name: "Sniff Event"},
    {id: 1353, name: "Hard Event"},
    {id: 1352, name: "Easy Event"},
    {id: 1351, name: "Dynamic Events"},
    {id: 1350, name: "Scavenger of the Wilds"},
    {id: 1349, name: "Lowland Spear Training"},
    {id: 1348, name: "Lowland Expertise"},
    {id: 1347, name: "Mastery Point"},
    {id: 1346, name: "Mastery Point"},
    {id: 1345, name: "Mastery Point"},
    {id: 1344, name: "Mastery Point"},
    {id: 1343, name: "Mastery Point"},
    {id: 1342, name: "Mastery Point"},
    {id: 1341, name: "Corruption Trait Line"},
    {id: 1340, name: "Elixir Gun"},
    {id: 1339, name: "Legendary Demon Stance"},
    {id: 1338, name: "Untamed Trait Line"},
    {id: 1337, name: "Explosives Trait Line"},
    {id: 1336, name: "Grenade Kit"},
    {id: 1335, name: "Flamethrower"},
    {id: 1334, name: "Bomb Kit"},
    {id: 1333, name: "Bladesworn Trait Line"},
    {id: 1332, name: "Dark Aura"},
    {id: 1330, name: "Forerunner of Death"},
    {id: 1329, name: "Tapped Out"},
    {id: 1328, name: "Monster Skill"},
    {id: 1327, name: "Water-Fire Attunement"},
    {id: 1326, name: "Water-Earth Attunement"},
    {id: 1325, name: "Water-Air Attunement"},
    {id: 1324, name: "Fire-Water Attunement"},
    {id: 1323, name: "Fire-Earth Attunement"},
    {id: 1322, name: "Fire-Air Attunement"},
    {id: 1321, name: "Earth-Water Attunement"},
    {id: 1320, name: "Earth-Fire Attunement"},
    {id: 1319, name: "Earth-Air Attunement"},
    {id: 1318, name: "Air-Water Attunement"},
    {id: 1317, name: "Air-Fire Attunement"},
    {id: 1316, name: "Air-Earth Attunement"},
    {id: 1315, name: "Water Attunement"},
    {id: 1314, name: "Fire Attunement"},
    {id: 1313, name: "Air Attunement"},
    {id: 1312, name: "Earth Attunement"},
    {id: 1311, name: "Resting in Chair"},
    {id: 1310, name: "Glider"},
    {id: 1309, name: "Spellbreaker Trait Line"},
    {id: 1308, name: "Guild Enhancement: Experience"},
    {id: 1307, name: "Nathan the Bartender"},
    {id: 1306, name: "Guild XP Gain"},
    {id: 1305, name: "Experience Enrichment"},
    {id: 1304, name: "Guild Experience Bonus"},
    {id: 1303, name: "Enhancement"},
    {id: 1302, name: "Journeyman Handiworker Crafting and Collection Boxes"},
    {id: 1301, name: "Novice Handiworker Crafting and Homestead Expansion"},
    {id: 1300, name: "Astral Amenities"},
    {id: 1299, name: "Globalization"},
    {id: 1298, name: "Resting"},
    {id: 1297, name: "Enlightenment"},
    {id: 1296, name: "New Year's Gift"},
    {id: 1295, name: "Festival Gobbler Boost"},
    {id: 1294, name: "Active Kill Streak!"},
    {id: 1293, name: "Guild Experience Boost"},
    {id: 1292, name: "Celebration Bonus"},
    {id: 1291, name: "Experience Bonus"},
    {id: 1290, name: "Attribute Bonus"},
    {id: 1289, name: "Ura"},
    {id: 1288, name: "Decima"},
    {id: 1287, name: "Greer"},
    {id: 1286, name: "All Experience"},
    {id: 1285, name: "Kill Experience"},
    {id: 1284, name: "tick"},
    {id: 1283, name: "x"},
    {id: 1281, name: "Projectile Destruction"},
    {id: 1280, name: "Ranged Damage"},
    {id: 1279, name: "Movement Speed"},
    {id: 1278, name: "Bee"},
    {id: 1277, name: "Boon Removal"},
    {id: 1276, name: "Magic Find"},
    {id: 1275, name: "Reflect Projectiles"},
    {id: 1274, name: "Block Projectiles"},
    {id: 1273, name: "AoE"},
    {id: 1256, name: "Magi's Insignia"},
    {id: 1255, name: "Band Together"},
    {id: 1254, name: "Sharp Edges"},
    {id: 1253, name: "Ring"},
    {id: 1252, name: "Headgear"},
    {id: 1251, name: "Honor Trait Line"},
    {id: 1250, name: "Decima"},
    {id: 1249, name: "Focused"},
    {id: 1248, name: "Charge"},
    {id: 1247, name: "Illuminated"},
    {id: 1246, name: "Warclaw"},
    {id: 1245, name: "Blade"},
    {id: 1244, name: "Clarity"},
    {id: 1243, name: "Trade Contract"},
    {id: 1242, name: "Skimmer"},
    {id: 1241, name: "Mastery Point"},
    {id: 1240, name: "Roller Beetle"},
    {id: 1239, name: "Jeweler"},
    {id: 1238, name: "Defiance Immunity"},
    {id: 1237, name: "Open World"},
    {id: 1236, name: "Marauder Insignia"},
    {id: 1235, name: "Berserker's Insignia"},
    {id: 1234, name: "Harrier's Insignia"},
    {id: 1233, name: "Viper's Insignia"},
    {id: 1232, name: "Celestial Insignia"},
    {id: 1231, name: "Sinister Insignia"},
    {id: 1230, name: "Cleric's Insignia"},
    {id: 1229, name: "Dragon's Insignia"},
    {id: 1228, name: "Assassin's Insignia"},
    {id: 1227, name: "Plaguedoctor's Insignia"},
    {id: 1226, name: "Minstrel's Insignia"},
    {id: 1225, name: "Giver's Insignia"},
    {id: 1224, name: "Ghastly Prison"},
    {id: 1223, name: "Player vs Player (PvP)"},
    {id: 1222, name: "Dungeon Armor and Weapons Merchant"},
    {id: 1221, name: "Contacts Menu"},
    {id: 1220, name: "Looking For Group (LFG)"},
    {id: 1219, name: "Ascalonian Catacombs (Ascalonian Tear)"},
    {id: 1218, name: "Currencies / Wallet / Vendor Sell"},
    {id: 1217, name: "Achievement Chest (milestone reward)"},
    {id: 1216, name: "Badge of Honor"},
    {id: 1215, name: "World vs World (WvW)"},
    {id: 1214, name: "Laurel"},
    {id: 1213, name: "Elementalist Icon Deprecated"},
    {id: 1212, name: "Elementalist Color Test"},
    {id: 1211, name: "Guild Panel"},
    {id: 1210, name: "Guild Commendation"},
    {id: 1209, name: "Guild"},
    {id: 1208, name: "Crafting"},
    {id: 1207, name: "Strike Mission"},
    {id: 1206, name: "Janthir Wilds (JW)"},
    {id: 1205, name: "ArenaNet"},
    {id: 1204, name: "Raid"},
    {id: 1203, name: "Fractals of the Mists"},
    {id: 1202, name: "Warclaw"},
    {id: 1201, name: "Spear"},
    {id: 1200, name: "Renown Heart"},
    {id: 1199, name: "Wizard's Vault Objectives"},
    {id: 1198, name: "Astral Acclaim"},
    {id: 1197, name: "Wizard's Vault"},
    {id: 1196, name: "End of Dragons"},
    {id: 1195, name: "Path of Fire (PoF)"},
    {id: 1194, name: "Heart of Thorns (HoT)"},
    {id: 1193, name: "Activity"},
    {id: 1192, name: "Story"},
    {id: 1191, name: "Rally / Revive"},
    {id: 1190, name: "Bank"},
    {id: 1189, name: "Inventory"},
    {id: 1188, name: "Bank"},
    {id: 1187, name: "Gems"},
    {id: 1186, name: "Currency Exchange"},
    {id: 1185, name: "Achievement Points"},
    {id: 1184, name: "Achievement Panel"},
    {id: 1183, name: "Gem Store"},
    {id: 1182, name: "Black Lion Trading Company"},
    {id: 1181, name: "Material Storage"},
    {id: 1180, name: "Wardrobe Storage"},
    {id: 1179, name: "Inventory / Gear / Hero Panel"},
    {id: 1178, name: "Trading Post"},
    {id: 1177, name: "Guild Wars 2"},
    {id: 1176, name: "Domination Trait Line"},
    {id: 1175, name: "Spinegazer"},
    {id: 1174, name: "Chair"},
    {id: 1173, name: "Earth Shield"},
    {id: 1172, name: "Frost Bow"},
    {id: 1171, name: "Lightning Hammer"},
    {id: 1170, name: "Fiery Greatsword"},
    {id: 1169, name: "Defeat"},
    {id: 1168, name: "Agony"},
    {id: 1167, name: "Pierce"},
    {id: 1166, name: "Block"},
    {id: 1165, name: "Electrical Repulsion"},
    {id: 1164, name: "Shrouded Ally"},
    {id: 1163, name: "Morphed"},
    {id: 1162, name: "Elemental Bullet"},
    {id: 1161, name: "Aether Hunter"},
    {id: 1160, name: "Wallow"},
    {id: 1159, name: "Phoenix"},
    {id: 1158, name: "Shark"},
    {id: 1157, name: "Armor Fish"},
    {id: 1156, name: "Black Widow Spider"},
    {id: 1155, name: "Jungle Spider"},
    {id: 1154, name: "Forest Spider"},
    {id: 1153, name: "Cave Spider"},
    {id: 1152, name: "Siamoth"},
    {id: 1151, name: "White Moa"},
    {id: 1150, name: "Rainbow Jellyfish"},
    {id: 1149, name: "Red Jellyfish"},
    {id: 1148, name: "Blue Jellyfish"},
    {id: 1147, name: "Sand Lion"},
    {id: 1146, name: "Cheetah"},
    {id: 1145, name: "Snow Leopard"},
    {id: 1144, name: "Jaguar"},
    {id: 1143, name: "Salamander Drake"},
    {id: 1142, name: "River Drake"},
    {id: 1141, name: "Reef Drake"},
    {id: 1140, name: "Marsh Drake"},
    {id: 1139, name: "Ice Drake"},
    {id: 1138, name: "Whiptail Devourer"},
    {id: 1137, name: "Lashtail Devourer"},
    {id: 1136, name: "Wolf"},
    {id: 1135, name: "Fern Hound"},
    {id: 1134, name: "Alpine Wolf"},
    {id: 1133, name: "White Raven"},
    {id: 1132, name: "Raven"},
    {id: 1131, name: "Owl"},
    {id: 1130, name: "Eagle"},
    {id: 1129, name: "Polar Bear"},
    {id: 1128, name: "Arctodus"},
    {id: 1127, name: "Sky-Chak Striker"},
    {id: 1126, name: "Defense Trait Line"},
    {id: 1125, name: "Earth Bullet"},
    {id: 1124, name: "Air Bullet"},
    {id: 1123, name: "Water Bullet"},
    {id: 1122, name: "Fire Bullet"},
    {id: 1121, name: "Crashing Courage"},
    {id: 1120, name: "Flowing Resolve"},
    {id: 1119, name: "Justice"},
    {id: 1118, name: "Spinning Axe"},
    {id: 1117, name: "Force of Nature"},
    {id: 1116, name: "Nature's Strength"},
    {id: 1115, name: "Upkeep"},
    {id: 1113, name: "Time Anchored"},
    {id: 1112, name: "On-kill Effect"},
    {id: 1111, name: "Secrets of the Obscure (SotO)"},
    {id: 1110, name: "Jade Bot Glide Booster"},
    {id: 1109, name: "Mount Stealth"},
    {id: 1108, name: "Woven Air"},
    {id: 1107, name: "Perfect Weave"},
    {id: 1106, name: "Charge"},
    {id: 1105, name: "Experience"},
    {id: 1104, name: "Loot"},
    {id: 1103, name: "Detonate Turret"},
    {id: 1102, name: "Condition Removal"},
    {id: 1101, name: "Fuse Time"},
    {id: 1100, name: "Stow Weapon"},
    {id: 1099, name: "Jade Protocol"},
    {id: 1098, name: "Hammer Orb"},
    {id: 1097, name: "Leave Transform"},
    {id: 1095, name: "Pet Unleashed"},
    {id: 1094, name: "Unleashed"},
    {id: 1093, name: "Throw Boulder"},
    {id: 1092, name: "Cruel Transformation"},
    {id: 1091, name: "Confusing Strikes"},
    {id: 1090, name: "Pig"},
    {id: 1089, name: "Set In Stone"},
    {id: 1088, name: "Catalyst Trait Line"},
    {id: 1087, name: "Mechanist Trait Line"},
    {id: 1086, name: "Firebrand Trait Line"},
    {id: 1085, name: "Willbender Trait Line"},
    {id: 1084, name: "Illusionary Inspiration"},
    {id: 1083, name: "Reaper Trait Line"},
    {id: 1082, name: "Carrion Devourer"},
    {id: 1081, name: "Rain's Nourishment"},
    {id: 1080, name: "Aquatic"},
    {id: 1079, name: "Light Aura"},
    {id: 1078, name: "Demonic Aura Timer"},
    {id: 1077, name: "Planetary Weight"},
    {id: 1076, name: "Demonic Aura"},
    {id: 1075, name: "Empowered"},
    {id: 1074, name: "Change"},
    {id: 1073, name: "Nerf"},
    {id: 1072, name: "Buff"},
    {id: 1071, name: "Retribution Trait Line"},
    {id: 1070, name: "Valor Trait Line"},
    {id: 1069, name: "Hyena"},
    {id: 1068, name: "Chaos Aura"},
    {id: 1067, name: "Arms Trait Line"},
    {id: 1066, name: "Alchemy Trait Line"},
    {id: 1065, name: "Prototype Indigo"},
    {id: 1064, name: "Prototype Arsenite"},
    {id: 1063, name: "Prototype Vermillion"},
    {id: 1062, name: "Power Transfer"},
    {id: 1061, name: "Tidal Torment"},
    {id: 1060, name: "Ergo Shear"},
    {id: 1059, name: "Ley Energy Shield"},
    {id: 1058, name: "Unblockable (effect)"},
    {id: 1057, name: "Spectre Trait Line"},
    {id: 1056, name: "Vindicator Trait Line"},
    {id: 1055, name: "Holosmith Trait Line"},
    {id: 1054, name: "Dagda"},
    {id: 1053, name: "Purifying Light"},
    {id: 1052, name: "Tome of Courage (effect)"},
    {id: 1051, name: "Tome of Resolve (effect)"},
    {id: 1050, name: "Tome of Justice (effect)"},
    {id: 1049, name: "Dormant Courage"},
    {id: 1048, name: "Dormant Resolve"},
    {id: 1047, name: "Dormant Justice"},
    {id: 1046, name: "Hawk"},
    {id: 1045, name: "Heat"},
    {id: 1044, name: "Empowered"},
    {id: 1043, name: "Insatiable"},
    {id: 1042, name: "Empowered"},
    {id: 1041, name: "Cerus"},
    {id: 1040, name: "Unstable Shield"},
    {id: 1039, name: "Death"},
    {id: 1038, name: "Drop Gunk"},
    {id: 1037, name: "Heal"},
    {id: 1036, name: "Zeal Trait Line"},
    {id: 1035, name: "Energized"},
    {id: 1034, name: "Shield of Earth"},
    {id: 1033, name: "Wreath of Flame"},
    {id: 1032, name: "Mushroom King's Blessing"},
    {id: 1031, name: "Molten Heart Toss"},
    {id: 1030, name: "Core Handler"},
    {id: 1029, name: "Fire Shield"},
    {id: 1028, name: "Fire Extinguisher Spray"},
    {id: 1027, name: "Shade"},
    {id: 1026, name: "Flow"},
    {id: 1025, name: "Auto Attack Chain"},
    {id: 1024, name: "White Tiger"},
    {id: 1023, name: "Jungle Stalker"},
    {id: 1022, name: "Siege Turtle"},
    {id: 1021, name: "Blue Moa"},
    {id: 1020, name: "Tranquil"},
    {id: 1019, name: "Bladesong"},
    {id: 1018, name: "Blade"},
    {id: 1017, name: "Nourishment"},
    {id: 1016, name: "Astral Force"},
    {id: 1015, name: "Page"},
    {id: 1014, name: "Distortion"},
    {id: 1013, name: "Shocking Aura"},
    {id: 1012, name: "Resonance Rifle Shot"},
    {id: 1011, name: "Radiation sickness as a result of exposure"},
    {id: 1010, name: "Magnetic Aura"},
    {id: 1009, name: "Scales of Jormag"},
    {id: 1008, name: "Rifle Butt"},
    {id: 1007, name: "Subvert"},
    {id: 1006, name: "Stealth Gliding"},
    {id: 1005, name: "Reinforced Armor"},
    {id: 1004, name: "Karma"},
    {id: 1003, name: "Sink"},
    {id: 1002, name: "Throw Water"},
    {id: 1001, name: "Envenom"},
    {id: 1000, name: "Poison Mushroom"},
    {id: 999, name: "Imbued Mushroom"},
    {id: 998, name: "Glenna"},
    {id: 997, name: "Big Boomer"},
    {id: 996, name: "Dungeon"},
    {id: 995, name: "Air Blast"},
    {id: 994, name: "Waypoint"},
    {id: 993, name: "Damage"},
    {id: 992, name: "Form Up and Advance!"},
    {id: 991, name: "Energy"},
    {id: 990, name: "Adrenaline"},
    {id: 989, name: "Lift Ectoplasm"},
    {id: 988, name: "Ghost Shield"},
    {id: 987, name: "Teleport Beacon"},
    {id: 986, name: "Lover's Embrace"},
    {id: 985, name: "Experience"},
    {id: 984, name: "Copper"},
    {id: 983, name: "Silver"},
    {id: 982, name: "Gold"},
    {id: 981, name: "catmander-blue"},
    {id: 980, name: "Commander"},
    {id: 979, name: "lfg"},
    {id: 978, name: "squad-lt"},
    {id: 977, name: "squad-com"},
    {id: 976, name: "lock"},
    {id: 975, name: "squad-share"},
    {id: 974, name: "cursor-hand"},
    {id: 973, name: "cursor"},
    {id: 972, name: "squad-broadcast"},
    {id: 971, name: "squad-people"},
    {id: 970, name: "squad-rc-no"},
    {id: 969, name: "squad-rc-yes"},
    {id: 968, name: "squad-rally"},
    {id: 967, name: "squad-attack"},
    {id: 966, name: "squad-defend"},
    {id: 965, name: "squad-resources"},
    {id: 964, name: "Extreme Vulnerability"},
    {id: 963, name: "Beastmastery Trait Line"},
    {id: 962, name: "Infirmity"},
    {id: 961, name: "Debilitated"},
    {id: 960, name: "Warhorn"},
    {id: 959, name: "Torch"},
    {id: 958, name: "Sword"},
    {id: 957, name: "Staff"},
    {id: 956, name: "Short Bow"},
    {id: 955, name: "Shield"},
    {id: 954, name: "Scepter"},
    {id: 953, name: "Rifle"},
    {id: 952, name: "Pistol"},
    {id: 951, name: "Mace"},
    {id: 950, name: "Longbow"},
    {id: 949, name: "Hammer"},
    {id: 948, name: "Greatsword"},
    {id: 947, name: "Focus"},
    {id: 946, name: "Dagger"},
    {id: 945, name: "Axe"},
    {id: 944, name: "Marked target"},
    {id: 943, name: "Shadow Force"},
    {id: 942, name: "Unblockable"},
    {id: 941, name: "Dragonvoid Zhaitan"},
    {id: 940, name: "Dragonvoid Soo Won"},
    {id: 939, name: "Dragonvoid Primordus"},
    {id: 938, name: "Dragonvoid Mordremoth"},
    {id: 937, name: "Dragonvoid Kralkatorrik"},
    {id: 936, name: "Dragonvoid Jormag"},
    {id: 935, name: "The Sniper"},
    {id: 934, name: "The Mech Rider"},
    {id: 933, name: "The Ritualist"},
    {id: 932, name: "The Mindblade"},
    {id: 931, name: "The Enforcer"},
    {id: 930, name: "Minister Li"},
    {id: 929, name: "Ankka"},
    {id: 928, name: "Scarlet Phantom"},
    {id: 927, name: "Echo of Scarlet Briar"},
    {id: 926, name: "Mai Trin"},
    {id: 925, name: "Varinia Stormsounder"},
    {id: 924, name: "Icebrood Goliath"},
    {id: 923, name: "Icebrood Beast"},
    {id: 922, name: "Corrupted Kodan"},
    {id: 921, name: "Boneskinner"},
    {id: 920, name: "Whisper of Jormag"},
    {id: 919, name: "Voice of the Fallen"},
    {id: 918, name: "Claw of the Fallen"},
    {id: 917, name: "Fraenir of Jormag"},
    {id: 916, name: "Icebrood Construct"},
    {id: 915, name: "Time in a Bottle"},
    {id: 914, name: "Blessing Seed"},
    {id: 913, name: "Drink Ambrosia"},
    {id: 912, name: "Throw Cursed Artifact"},
    {id: 911, name: "Throw Unstable Reagent"},
    {id: 910, name: "Throw Enchanted Ice"},
    {id: 909, name: "Float"},
    {id: 908, name: "Venom"},
    {id: 907, name: "Chaos Trait Line"},
    {id: 906, name: "Explosion"},
    {id: 905, name: "Tempest Trait Line"},
    {id: 904, name: "Combo Field"},
    {id: 903, name: "Tale of Dungeon Delving"},
    {id: 902, name: "Untamed"},
    {id: 901, name: "Rock Gazelle"},
    {id: 900, name: "Mechanist"},
    {id: 899, name: "Virtuoso"},
    {id: 898, name: "Catalyst"},
    {id: 897, name: "Bladesworn"},
    {id: 896, name: "Spectre"},
    {id: 895, name: "Vindicator"},
    {id: 894, name: "Haunt Shot"},
    {id: 893, name: "Grasping Shadows"},
    {id: 892, name: "Eternal Night"},
    {id: 891, name: "Mind Shock"},
    {id: 890, name: "Dawn's Repose"},
    {id: 889, name: "Harbinger"},
    {id: 888, name: "Positive Flow"},
    {id: 887, name: "Flicker Step"},
    {id: 886, name: "Triggerguard"},
    {id: 885, name: "Dragon Slash—Reach"},
    {id: 884, name: "Dragon Slash—Boost"},
    {id: 883, name: "Dragon Slash—Force"},
    {id: 882, name: "Break Step"},
    {id: 881, name: "Cyclone Trigger"},
    {id: 880, name: "Artillery Slash"},
    {id: 879, name: "Blooming Fire"},
    {id: 878, name: "Explosive Thrust"},
    {id: 877, name: "Steel Divide"},
    {id: 876, name: "Swift Cut"},
    {id: 874, name: "Willbender"},
    {id: 873, name: "Immobilizing"},
    {id: 871, name: "Raptor"},
    {id: 870, name: "Arcing Affliction"},
    {id: 869, name: "Canyon Jumping"},
    {id: 868, name: "Nuhoch Stealth Detection"},
    {id: 867, name: "Residual Affliction"},
    {id: 865, name: "Shifting Sands"},
    {id: 861, name: "Spirit Woods"},
    {id: 860, name: "Explosive Launch"},
    {id: 859, name: "X"},
    {id: 858, name: "Triangle"},
    {id: 857, name: "Star"},
    {id: 856, name: "Square"},
    {id: 855, name: "Spiral"},
    {id: 854, name: "Arrow"},
    {id: 853, name: "Circle"},
    {id: 852, name: "Heart"},
    {id: 848, name: "Beehive"},
    {id: 847, name: "Oil Kegs"},
    {id: 846, name: "Oil Keg"},
    {id: 844, name: "Mursaat Overseer's"},
    {id: 841, name: "Eroding Curse"},
    {id: 840, name: "Springer's"},
    {id: 839, name: "Jackal"},
    {id: 838, name: "High Vault"},
    {id: 837, name: "Lean Techniques"},
    {id: 836, name: "Springer"},
    {id: 835, name: "Griffon"},
    {id: 834, name: "Skyscale"},
    {id: 828, name: "Eater of Souls"},
    {id: 827, name: "Eyes"},
    {id: 826, name: "Eye of Judgment"},
    {id: 825, name: "Eye of Fate"},
    {id: 824, name: "River of Souls"},
    {id: 823, name: "Broken King's"},
    {id: 822, name: "Broken King"},
    {id: 819, name: "Lost Spirit"},
    {id: 818, name: "Light Thieves"},
    {id: 817, name: "Light Thief"},
    {id: 816, name: "Spirit Horde"},
    {id: 814, name: "Twisted Spirit"},
    {id: 813, name: "Energy Threshold"},
    {id: 812, name: "Mortal Coil"},
    {id: 811, name: "Spirit Surge"},
    {id: 810, name: "Descend"},
    {id: 809, name: "Ascend"},
    {id: 808, name: "Reclaimed Energy"},
    {id: 807, name: "Fractured Spirit"},
    {id: 806, name: "Light Orb's"},
    {id: 805, name: "Light Orbs"},
    {id: 804, name: "Light Orb"},
    {id: 803, name: "Exposed"},
    {id: 802, name: "Empowered"},
    {id: 801, name: "Flare"},
    {id: 800, name: "Throw Light"},
    {id: 799, name: "Minotaurs"},
    {id: 798, name: "Minotaur"},
    {id: 796, name: "Frozen Wind"},
    {id: 795, name: "Statues of Grenth"},
    {id: 794, name: "Destroyer's"},
    {id: 792, name: "Fiery Surge"},
    {id: 791, name: "Ice Elemental"},
    {id: 790, name: "Apocalypse Bringer"},
    {id: 788, name: "Pyre Guardian"},
    {id: 786, name: "Greater Magma Elemental"},
    {id: 783, name: "Exile's Embrace"},
    {id: 782, name: "Wurm Spit"},
    {id: 781, name: "Elite Flesh Wurms"},
    {id: 780, name: "Chilling Aura"},
    {id: 779, name: "Corrupt the Living"},
    {id: 778, name: "Slice"},
    {id: 777, name: "Hand of Eruption"},
    {id: 776, name: "Hand of Erosion"},
    {id: 775, name: "Sand Geyser"},
    {id: 774, name: "Radiant Blindness"},
    {id: 773, name: "Pillar Pandemonium"},
    {id: 772, name: "Waterlogged"},
    {id: 771, name: "Soul Siphon"},
    {id: 770, name: "Spirit Hordes"},
    {id: 769, name: "Rift Force"},
    {id: 767, name: "Surging Souls"},
    {id: 766, name: "Soulless Horror"},
    {id: 765, name: "Issue Challenge"},
    {id: 764, name: "Necrosis"},
    {id: 763, name: "Spinning Scythes"},
    {id: 762, name: "Death Bloom"},
    {id: 761, name: "Howling Death"},
    {id: 760, name: "Tormented Dead"},
    {id: 759, name: "Saul the Drunkard"},
    {id: 758, name: "Saul the Gambler"},
    {id: 757, name: "Demonic Tears"},
    {id: 756, name: "Saul the Thief"},
    {id: 755, name: "Weak Minded"},
    {id: 754, name: "Pride"},
    {id: 752, name: "Greed"},
    {id: 750, name: "Devour"},
    {id: 749, name: "Saul"},
    {id: 748, name: "Spirit Scream"},
    {id: 747, name: "Ripper"},
    {id: 746, name: "Shark Splash"},
    {id: 745, name: "Dreg Shark"},
    {id: 744, name: "Dreg Shark Extractor"},
    {id: 743, name: "Zommoros"},
    {id: 742, name: "Mega Princess Doll"},
    {id: 741, name: "Mega Foostivoo the Merry"},
    {id: 740, name: "Mega Maraca Choya Pinata"},
    {id: 739, name: "Mega Chainsaw the Skeleton"},
    {id: 737, name: "Ectoplasmic Conglomeration"},
    {id: 736, name: "Otherworldly Defenses"},
    {id: 734, name: "Conjured Warrior"},
    {id: 733, name: "Conjured Slash"},
    {id: 732, name: "Junk Wall"},
    {id: 731, name: "Conjured Protection"},
    {id: 730, name: "Conjured Shield"},
    {id: 729, name: "Greatsword Power"},
    {id: 727, name: "Conjured Shield"},
    {id: 725, name: "Conjured Greatsword"},
    {id: 724, name: "Conjured Amalgamate"},
    {id: 723, name: "Hollowed Bomber"},
    {id: 722, name: "Time Bomb"},
    {id: 721, name: "Spatial Rifts"},
    {id: 720, name: "Enervator"},
    {id: 719, name: "Desmina's"},
    {id: 718, name: "Expel Energy"},
    {id: 717, name: "Flesh Golems"},
    {id: 716, name: "Deathlings"},
    {id: 714, name: "Enforcer"},
    {id: 713, name: "Desmina"},
    {id: 711, name: "Messenger"},
    {id: 709, name: "Reaper"},
    {id: 708, name: "Unseen Burden"},
    {id: 707, name: "Celestial Dash"},
    {id: 706, name: "Cairn's"},
    {id: 705, name: "Bloodstone Shard"},
    {id: 704, name: "Hero's Return"},
    {id: 703, name: "Deadly Attack"},
    {id: 702, name: "Charged Bloodstone"},
    {id: 700, name: "Intervention"},
    {id: 699, name: "Bloodstone Blessed"},
    {id: 698, name: "Shifting Chaos"},
    {id: 697, name: "Twisting Chaos"},
    {id: 696, name: "Bending Chaos"},
    {id: 694, name: "Exquisite Conjuctions"},
    {id: 693, name: "Bloodstone Fragment"},
    {id: 692, name: "Derangement"},
    {id: 690, name: "Haunting Statue"},
    {id: 689, name: "Chaotic Haze"},
    {id: 688, name: "Still Waters"},
    {id: 687, name: "Madness"},
    {id: 686, name: "Oil Slick"},
    {id: 685, name: "Mortar"},
    {id: 684, name: "Saboteur"},
    {id: 683, name: "Mordremoth's Smash"},
    {id: 682, name: "Mortars"},
    {id: 681, name: "Saboteurs"},
    {id: 680, name: "Oil Kegs"},
    {id: 679, name: "Beehives"},
    {id: 678, name: "Chaos Corrosion"},
    {id: 677, name: "Enfeebled Force"},
    {id: 676, name: "Flare-Up"},
    {id: 675, name: "Power Share"},
    {id: 674, name: "Battering Blitz"},
    {id: 671, name: "Kinetic Abundance"},
    {id: 670, name: "Flux Disruptor"},
    {id: 669, name: "Entropic Distortion"},
    {id: 668, name: "Sapping Surge"},
    {id: 667, name: "Immobilized"},
    {id: 666, name: "Momentum"},
    {id: 665, name: "Updraft Use"},
    {id: 664, name: "Eye of the Storm"},
    {id: 663, name: "Repulsion Field"},
    {id: 662, name: "Ion Shield"},
    {id: 660, name: "Flash Discharge"},
    {id: 659, name: "Voltaic Wisps"},
    {id: 658, name: "Voltaic Wisp"},
    {id: 657, name: "Paralyzing Wisps"},
    {id: 656, name: "Paralyzing Wisp"},
    {id: 653, name: "Blight"},
    {id: 650, name: "Magic Blast Intensity"},
    {id: 649, name: "Xera's Boon"},
    {id: 648, name: "Xera's Embrace"},
    {id: 646, name: "Keep Construct's"},
    {id: 644, name: "Bloodstone Turret"},
    {id: 643, name: "Stealths"},
    {id: 641, name: "McLeod the Silent"},
    {id: 640, name: "Ley Line Gliding"},
    {id: 639, name: "Healing Cleanse"},
    {id: 638, name: "Toxic Spores"},
    {id: 637, name: "Over Here!"},
    {id: 636, name: "Surveilled"},
    {id: 635, name: "Forsaken Magic"},
    {id: 634, name: "Warg Bloodhound's"},
    {id: 633, name: "Warg Bloodhounds"},
    {id: 632, name: "Forsaken Thicket Waters"},
    {id: 631, name: "Blood Shield"},
    {id: 630, name: "Heat Wave"},
    {id: 629, name: "Fears"},
    {id: 628, name: "Tormented Heart"},
    {id: 626, name: "Strengthened Bond: Rigom"},
    {id: 625, name: "Strengthened Bond: Guldhem"},
    {id: 624, name: "Fanatical Resilience"},
    {id: 623, name: "Tear Instability"},
    {id: 622, name: "Classic Misdirection"},
    {id: 621, name: "Rigom"},
    {id: 617, name: "Guldhem"},
    {id: 614, name: "Protected Heart"},
    {id: 613, name: "Protect"},
    {id: 612, name: "Claim"},
    {id: 611, name: "Dispel"},
    {id: 610, name: "Mursaat Overseer's Shield"},
    {id: 606, name: "Jade Soldier"},
    {id: 605, name: "Narcolepsy"},
    {id: 604, name: "Magic Transformation"},
    {id: 603, name: "Nauseated"},
    {id: 602, name: "Stealthing"},
    {id: 601, name: "Eat"},
    {id: 600, name: "Evolved Slublings"},
    {id: 599, name: "Protective Shadow"},
    {id: 598, name: "Krytan Drakehound"},
    {id: 597, name: "Carrion Devourer"},
    {id: 596, name: "Murellow"},
    {id: 595, name: "Pink Moa"},
    {id: 594, name: "Boar"},
    {id: 593, name: "Tiger"},
    {id: 592, name: "Black Moa"},
    {id: 591, name: "Fire Wyvern"},
    {id: 590, name: "Fire Drake"},
    {id: 589, name: "Kernan's"},
    {id: 588, name: "Shell-Shocked"},
    {id: 585, name: "Updraft"},
    {id: 584, name: "Spectral Darkness"},
    {id: 583, name: "Spirited Fusion"},
    {id: 582, name: "Fractured"},
    {id: 581, name: "Erratic Energy"},
    {id: 580, name: "Compromised"},
    {id: 579, name: "Skorvald The Shattered"},
    {id: 578, name: "Exposed"},
    {id: 577, name: "No Pain No Gain"},
    {id: 574, name: "Level-80 Boost"},
    {id: 573, name: "Unstable Rift"},
    {id: 571, name: "Inventions Trait Line"},
    {id: 570, name: "Inventions"},
    {id: 569, name: "Firearms Trait Line"},
    {id: 567, name: "Tools"},
    {id: 566, name: "Bouncing Mushroom"},
    {id: 565, name: "Adrenal Mushrooms"},
    {id: 564, name: "Bouncing Mushrooms"},
    {id: 563, name: "Glider Basics"},
    {id: 562, name: "Karde's"},
    {id: 561, name: "Strength Trait Line"},
    {id: 560, name: "Strength"},
    {id: 559, name: "Tactics Trait Line"},
    {id: 558, name: "Tactics"},
    {id: 557, name: "Berserker Trait Line"},
    {id: 556, name: "Discipline Trait Line"},
    {id: 555, name: "Discipline"},
    {id: 553, name: "Daredevil"},
    {id: 552, name: "Thieves"},
    {id: 550, name: "Strength Trait Line"},
    {id: 549, name: "Strength"},
    {id: 548, name: "Tactics Trait Line"},
    {id: 547, name: "Tactics"},
    {id: 545, name: "Ammunition Skill"},
    {id: 544, name: "Ammunition"},
    {id: 542, name: "Slothasor's"},
    {id: 541, name: "Weaver Trait Line"},
    {id: 539, name: "Soulless Horror's"},
    {id: 538, name: "Perfect Weave"},
    {id: 531, name: "Inspiring Virtue"},
    {id: 527, name: "Wisp's"},
    {id: 526, name: "Earth Trait Line"},
    {id: 525, name: "Earth"},
    {id: 523, name: "Arcane Trait Line"},
    {id: 522, name: "Arcane"},
    {id: 521, name: "Fire Trait Line"},
    {id: 519, name: "Water Trait Line"},
    {id: 518, name: "Water"},
    {id: 517, name: "Air Trait Line"},
    {id: 516, name: "Air"},
    {id: 514, name: "Magnetic Aura"},
    {id: 513, name: "Shocking Aura"},
    {id: 512, name: "Frost Aura"},
    {id: 511, name: "Fire Aura"},
    {id: 501, name: "Weaver"},
    {id: 494, name: "Tempest"},
    {id: 493, name: "Salvation Trait Line"},
    {id: 492, name: "Vivid Echo"},
    {id: 491, name: "Devastation Trait Line"},
    {id: 490, name: "Battle Scars"},
    {id: 487, name: "Renegade Trait Line"},
    {id: 486, name: "Kalla's Fervor"},
    {id: 485, name: "Invocation Trait Line"},
    {id: 484, name: "Volatile Poison"},
    {id: 483, name: "Updrafts"},
    {id: 482, name: "Herald Trait Line"},
    {id: 481, name: "Unbalanced"},
    {id: 479, name: "Dhuum's"},
    {id: 478, name: "Kenut's"},
    {id: 477, name: "Nikare's"},
    {id: 475, name: "Mirage Trait Line"},
    {id: 474, name: "Mirage Cloak"},
    {id: 473, name: "Illusions Trait Line"},
    {id: 470, name: "Broken King"},
    {id: 468, name: "Feared"},
    {id: 467, name: "Blue Pylon Power"},
    {id: 465, name: "Mirage"},
    {id: 464, name: "Chronomancer"},
    {id: 463, name: "Chronomancer Trait Line"},
    {id: 454, name: "Epilogue: Ashes of the Just"},
    {id: 453, name: "Chapter 4: Scorched Aftermath"},
    {id: 452, name: "Chapter 2: Igniting Burst"},
    {id: 451, name: "Chapter 1: Searing Spell"},
    {id: 448, name: "Chapter 1: Unflinching Charge"},
    {id: 447, name: "Chapter 2: Daring Challenge"},
    {id: 446, name: "Chapter 3: Valiant Bulwark"},
    {id: 445, name: "Chapter 4: Stalwart Stand"},
    {id: 444, name: "Epilogue: Unbroken Lines"},
    {id: 443, name: "Chapter 1: Desert Bloom"},
    {id: 442, name: "Chapter 2: Radiant Recovery"},
    {id: 441, name: "Chapter 3: Azure Sun"},
    {id: 440, name: "Epilogue: Eternal Oasis"},
    {id: 439, name: "Chapter 4: Shining River"},
    {id: 438, name: "Chapter 3: Heated Rebuke"},
    {id: 437, name: "Range"},
    {id: 436, name: "Radius"},
    {id: 434, name: "Mesmer"},
    {id: 433, name: "Crippled"},
    {id: 432, name: "Reveals"},
    {id: 431, name: "Reveal"},
    {id: 430, name: "Dragonhunter Trait Line"},
    {id: 429, name: "Sabetha's"},
    {id: 428, name: "Blinds"},
    {id: 427, name: "Virtues Trait Line"},
    {id: 425, name: "Radiance Trait Line"},
    {id: 423, name: "Inspiration Trait Line"},
    {id: 422, name: "Inspiration"},
    {id: 421, name: "Dueling Trait Line"},
    {id: 419, name: "Blinding"},
    {id: 418, name: "Spiders"},
    {id: 417, name: "Spider"},
    {id: 416, name: "Launch"},
    {id: 413, name: "Tools Trait Line"},
    {id: 412, name: "Scrapper Trait Line"},
    {id: 411, name: "Armor"},
    {id: 410, name: "Deadeye Trait Line"},
    {id: 408, name: "Elementalist"},
    {id: 406, name: "Deadeye"},
    {id: 401, name: "Narella"},
    {id: 400, name: "Zane"},
    {id: 399, name: "Berg"},
    {id: 398, name: "Kernan"},
    {id: 397, name: "Ground-Targeted"},
    {id: 396, name: "Throw Magnetic Bomb"},
    {id: 395, name: "Revive"},
    {id: 394, name: "Dazing"},
    {id: 393, name: "Dazes"},
    {id: 392, name: "Dazed"},
    {id: 391, name: "Daze"},
    {id: 389, name: "Acrobatics Trait Line"},
    {id: 388, name: "Shadow Arts Trait Line"},
    {id: 387, name: "Critical Strikes Trait Line"},
    {id: 386, name: "Deadly Arts Trait Line"},
    {id: 385, name: "Trickery Trait Line"},
    {id: 384, name: "Daredevil Trait Line"},
    {id: 383, name: "Blood Shield"},
    {id: 382, name: "Blood Fueled"},
    {id: 381, name: "Detonate Plasmas"},
    {id: 380, name: "Broken King"},
    {id: 379, name: "Thieves"},
    {id: 378, name: "Thief"},
    {id: 377, name: "Stolen Skill"},
    {id: 376, name: "Revealed"},
    {id: 375, name: "Endurance"},
    {id: 374, name: "Initiative"},
    {id: 373, name: "Malice"},
    {id: 372, name: "Unstable Artifact"},
    {id: 371, name: "Soul Stone Venom"},
    {id: 370, name: "Detonate Plasma"},
    {id: 369, name: "Attack of Opportunity"},
    {id: 368, name: "Evading"},
    {id: 366, name: "Evade"},
    {id: 365, name: "Snowstorm"},
    {id: 364, name: "Supportive"},
    {id: 363, name: "Ferocious"},
    {id: 362, name: "Versatile"},
    {id: 361, name: "Deadly"},
    {id: 360, name: "Lynx"},
    {id: 359, name: "Soulbeast Trait Line"},
    {id: 358, name: "Stout"},
    {id: 357, name: "Blue Moa"},
    {id: 356, name: "Black Bear"},
    {id: 355, name: "Wisps"},
    {id: 354, name: "Wisp"},
    {id: 353, name: "Violent Currents"},
    {id: 352, name: "Superspeed"},
    {id: 351, name: "Stealthed"},
    {id: 350, name: "Stealth"},
    {id: 349, name: "Unnatural Signet"},
    {id: 347, name: "Fixated"},
    {id: 346, name: "Resolution"},
    {id: 345, name: "Blue Attunement"},
    {id: 344, name: "Jacaranda"},
    {id: 343, name: "Vitality"},
    {id: 342, name: "Blood Magic Trait Line"},
    {id: 341, name: "Barriers"},
    {id: 340, name: "Claimed"},
    {id: 339, name: "Claim"},
    {id: 338, name: "Karde"},
    {id: 337, name: "Blinded"},
    {id: 336, name: "Samarog"},
    {id: 335, name: "Knuckles"},
    {id: 333, name: "Keep Construct"},
    {id: 331, name: "Anomalies"},
    {id: 330, name: "Anomaly"},
    {id: 329, name: "Qadim the Peerless"},
    {id: 326, name: "Knockback"},
    {id: 324, name: "Wyverns"},
    {id: 323, name: "Wyvern"},
    {id: 322, name: "Wyvern Patriarch"},
    {id: 321, name: "Wyvern Matriarch"},
    {id: 320, name: "Destroyer"},
    {id: 319, name: "Hydra"},
    {id: 317, name: "Lava Elemental"},
    {id: 316, name: "Qadim"},
    {id: 315, name: "Nikare"},
    {id: 314, name: "Kenut"},
    {id: 313, name: "Mursaat Overseer"},
    {id: 311, name: "Jade Knight"},
    {id: 309, name: "Jade Scout"},
    {id: 308, name: "Invulnerable"},
    {id: 307, name: "Downpour"},
    {id: 305, name: "Slubling"},
    {id: 304, name: "Sapper Bombs"},
    {id: 303, name: "Sapper Bomb"},
    {id: 301, name: "Charged Soul"},
    {id: 296, name: "Knockdown"},
    {id: 295, name: "Green Guardian"},
    {id: 294, name: "Red Guardian"},
    {id: 293, name: "Blue Guardian"},
    {id: 292, name: "Slothasor"},
    {id: 290, name: "Death's Carapace"},
    {id: 289, name: "Twin Largos"},
    {id: 288, name: "Xera"},
    {id: 287, name: "Matthias"},
    {id: 286, name: "Toughness"},
    {id: 285, name: "Soul Reaping Trait Line"},
    {id: 284, name: "Scourge Trait Line"},
    {id: 283, name: "Cardinal Adina"},
    {id: 282, name: "Cardinal Sabir"},
    {id: 281, name: "Soulless Horror"},
    {id: 280, name: "Dhuum"},
    {id: 279, name: "Death Magic Trait Line"},
    {id: 278, name: "Curses Trait Line"},
    {id: 277, name: "Condition Duration"},
    {id: 275, name: "Soulbeast"},
    {id: 272, name: "Wilderness Survival Trait Line"},
    {id: 271, name: "Skirmishing Trait Line"},
    {id: 270, name: "Marksmanship Trait Line"},
    {id: 266, name: "Stun"},
    {id: 264, name: "Recharge"},
    {id: 263, name: "Stun Break"},
    {id: 262, name: "Gorseval"},
    {id: 261, name: "Vale Guardian"},
    {id: 260, name: "Seeker"},
    {id: 259, name: "Warg Bloodhound"},
    {id: 258, name: "Siege the Stronghold"},
    {id: 257, name: "Pushed"},
    {id: 256, name: "Pushing"},
    {id: 255, name: "Pushes"},
    {id: 254, name: "Push"},
    {id: 250, name: "Pull"},
    {id: 249, name: "Cairn"},
    {id: 248, name: "Sabetha"},
    {id: 247, name: "Nature Magic Trait Line"},
    {id: 246, name: "Druid Trait Line"},
    {id: 245, name: "Healing Power"},
    {id: 244, name: "Boon Duration"},
    {id: 243, name: "Critical Chance"},
    {id: 242, name: "Critical Damage"},
    {id: 241, name: "Ferocity"},
    {id: 240, name: "Precision"},
    {id: 239, name: "Expertise"},
    {id: 238, name: "Condition Damage"},
    {id: 237, name: "Concentration"},
    {id: 236, name: "Power"},
    {id: 235, name: "Electric Wyvern"},
    {id: 234, name: "Brown Bear"},
    {id: 233, name: "Smokescale"},
    {id: 231, name: "Fanged Iboga"},
    {id: 230, name: "Swap Pets"},
    {id: 229, name: "Activate Pet"},
    {id: 228, name: "Stow Pet"},
    {id: 227, name: "Avoid Combat"},
    {id: 226, name: "Guard"},
    {id: 225, name: "Return to Me"},
    {id: 224, name: "Attack My Target"},
    {id: 223, name: "Ranger"},
    {id: 215, name: "Deimos"},
    {id: 214, name: "Bristleback"},
    {id: 213, name: "Red Moa"},
    {id: 212, name: "Warthog"},
    {id: 210, name: "Druid"},
    {id: 207, name: "Dodge"},
    {id: 204, name: "Down"},
    {id: 202, name: "Weapon Swap"},
    {id: 199, name: "Cooldown"},
    {id: 198, name: "Scourge"},
    {id: 197, name: "Reaper"},
    {id: 196, name: "Defiance Break"},
    {id: 195, name: "Necromancer"},
    {id: 194, name: "Life Force"},
    {id: 163, name: "Boon Thieves"},
    {id: 138, name: "Holosmith"},
    {id: 126, name: "Scrapper"},
    {id: 120, name: "Engineer"},
    {id: 108, name: "Spellbreaker"},
    {id: 98, name: "Berserker"},
    {id: 88, name: "Warrior"},
    {id: 78, name: "Renegade"},
    {id: 68, name: "Herald"},
    {id: 60, name: "Revenant"},
    {id: 48, name: "Firebrand"},
    {id: 40, name: "Dragonhunter"},
    {id: 28, name: "Guardian"},
    {id: 27, name: "Immobilize"},
    {id: 26, name: "Taunt"},
    {id: 25, name: "Torment"},
    {id: 24, name: "Bleeding"},
    {id: 23, name: "Cripple"},
    {id: 22, name: "Fear"},
    {id: 21, name: "Confusion"},
    {id: 20, name: "Poison"},
    {id: 19, name: "Slow"},
    {id: 18, name: "Vulnerability"},
    {id: 17, name: "Weakness"},
    {id: 16, name: "Blind"},
    {id: 15, name: "Chilled"},
    {id: 14, name: "Burning"},
    {id: 13, name: "Vigor"},
    {id: 12, name: "Swiftness"},
    {id: 11, name: "Stability"},
    {id: 9, name: "Resistance"},
    {id: 8, name: "Regeneration"},
    {id: 7, name: "Quickness"},
    {id: 6, name: "Protection"},
    {id: 5, name: "Might"},
    {id: 4, name: "Fury"},
    {id: 3, name: "Barrier"},
    {id: 2, name: "Alacrity"},
    {id: 1, name: "Aegis"}
];